In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
a=[1,2,3,4] #리스트
b=[1,2,3,4]
print(a+b)

a=np.array([1,2,3,4]) #행렬
b=np.array([1,2,3,4])
print(a+b)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [4]:
import numpy as np #산술연산

a=np.array([1,2,3,4])
b=np.array([.4,.4,.3,.2])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[1.4 2.4 3.3 4.2]
[0.6 1.6 2.7 3.8]
[0.4 0.8 0.9 0.8]
[ 2.5  5.  10.  20. ]


In [5]:
#2차원 배열과 행렬
import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [6]:
#행렬의 곱
import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(np.dot(A,B))

[[ 7 10]
 [15 22]]


In [9]:
#브로드캐스트1
import numpy as np

A=np.array([[1,2],
           [3,4]])
B=np.array([[1,2],
           [3,4]])
print(A+B)
print("-"*10)

B=np.array([[1,2]])
print(A+B)
print("-"*10)

B=np.array([[1],
           [2]])
print(A+B)
print("-"*10)

B=2
print(A+B)

[[2 4]
 [6 8]]
----------
[[2 4]
 [4 6]]
----------
[[2 3]
 [5 6]]
----------
[[3 4]
 [5 6]]


In [10]:
#브로드캐스트2
A=np.array([[1,2],
           [3,4]])
B=np.array([[1,2]])
print((A+B))

[[2 4]
 [4 6]]


In [11]:
#브로드캐스트3
A=np.array([[1,2],
           [3,4]])
B=np.array([[1],
           [2]])
print((A+B))

[[2 3]
 [5 6]]


In [12]:
#브로드캐스트4
A=np.array([[1,2],
           [3,4]])
B=2
print((A+B))

[[3 4]
 [5 6]]
